name: Sync SCP data

on:
  workflow_dispatch:
  schedule:
    - cron: "30 5 * * *"

permissions:
  contents: write

jobs:
  sync-scp-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v6

      - name: Checkout SCP data repo
        uses: actions/checkout@v6
        with:
          repository: sixeightyfour/scp-json-sync
          path: scp-json-sync

      - name: Prepare destination folders
        run: |
          mkdir -p demos-build/assets/

      - name: Copy merged JSON
        run: |
          if [ -f scp-json-sync/output/merged/all_pages.json ]; then
            cp scp-json-sync/output/merged/all_pages.json demos-build/assets/all_pages.json
          else
            echo "Missing merged file: scp-json-sync/output/merged/all_pages.json"
            exit 1
          fi

      - name: Show copied files
        run: |
          echo "Copied files:"
          find demos-build/assets -type f | sort

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/scp

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Sync SCP data"
            git push
          fi
